### ISSUE TITLE
Set up github actions and structure

### ISSUE THREAD

**Issue by u22633601** [u22633601/MP-13#3]
Set up the github actions and which ones we are using. Also decide on the github structure if it's one or two branches, how the branches should be named, how the pull requests should be handled and if they shouldrebase or merge branches, just set up the structure in all that, and the reasoning behind it.

**Comment by waveyboym** [comment]
Tracking: https://github.com/u22633601/MP-13/tree/devops-bootstrapped-project-template/.github/workflows
